mongo:
  image: mongo
  ports:
    - "27017:27017"


rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"


windopt:
  build: .
  links:
    - mongo
    - rabbitmq
  ports:
    - "80:80"
  environment:
    - MONGO_URI=mongo:27017
    - ENV_NAME=local
    - BROKER_BASE=rabbitmq