rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"

windopt:
  image: huevosabio/windopt:master
  env_file: .env
  links:
    - rabbitmq
  ports:
  - "8000:80"
  environment:
  - MONGO_URI=ds047095.mongolab.com:47095/windops
  - ENV_NAME=production
  - DB_USER=stanford
  - DB_PWD=mortenson
  - BROKER_BASE=rabbitmq
